name: efood_multivendor
description: A new Flutter application.
publish_to: 'none' #
version: 1.0.0+10

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get: ^4.6.5
  hexcolor:
  shared_preferences: ^2.0.11
  cloud_firestore: 
  connectivity: ^3.0.6
  firebase_core: ^1.2.1
  firebase_messaging: ^11.2.4
  flutter_local_notifications: ^9.1.5
  path_provider: ^2.0.8
  url_strategy: ^0.2.0
  pin_code_fields: ^7.4.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.1.1
  google_maps_flutter_web: ^0.4.0+3
  flutter_typeahead: ^4.0.0
  carousel_slider: ^4.0.0
  shimmer_animation: ^2.1.0+1
  image_picker: ^0.8.4+4
  universal_html: ^2.0.8
  universal_ui: ^0.0.8
  webview_flutter: ^3.0.0
  flutter_widget_from_html_core: ^0.8.5+3
  url_launcher: ^6.0.17
  http: ^0.13.4
  pointer_interceptor: ^0.9.0+1
  phone_number:
  #  ^1.0.0
  country_code_picker: ^2.0.2
  cached_network_image: ^3.2.1
  modal_bottom_sheet: ^2.0.1
  share_plus: ^6.3.0
  uni_links: ^0.5.1
  flutter_rating_bar: ^4.0.1
  #  google_sign_in: ^5.2.1
#  flutter_facebook_auth: ^3.5.7

dev_dependencies:
  change_app_package_name: ^1.1.0

  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/font/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/font/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/font/Tajawal-Black.ttf
          weight: 900